export const typeOptions = [
	'Planet',
	'Space station',
	'Microverse',
	'TV',
	'Resort',
	'Fantasy town',
	'Dream',
	'Dimension',
	'Menagerie',
	'Game',
	'Customs',
	'Daycare',
	'Dwarf planet (Celestial Dwarf)',
	'Box',
	'Spacecraft',
	'Artificially generated world',
	'Machine',
	'Arcade',
	'Quadrant',
	'Quasar',
	'Mount',
	'Convention',
	'Diegesis',
	'Nightmare',
	'Asteroid',
	'Acid plant',
	'Reality',
	'Death Star',
	'Base',
	'Elemental Rings',
	'Human',
	'Hell',
	'Police Department',
	'Country',
	'Consciousness',
	'Memory',
]

export const dimensionOptions = [
	'Dimension C-137',
	'Post-Apocalyptic Dimension',
	'Replacement Dimension',
	'Cronenberg Dimension',
	'Fantasy Dimension',
	'Dimension 5-126',
	'Testicle Monster Dimension',
	'Unknown',
	'Dimension C-500A',
	'Dimension K-83',
	'Dimension J19ζ7',
	'Dimension D-99',
	'Dimension D716',
	'Dimension D716-B',
	'Dimension D716-C',
	'Dimension J-22',
	'Dimension C-35',
	'Pizza Dimension',
	'Phone Dimension',
	'Chair Dimension',
	'Fascist Dimension',
	'Fascist Teddy Bear Dimension',
	'Wasp Dimension',
	'Tusk Dimension',
	'Magic Dimension',
	'Merged Dimension',
]
